### ISSUE TITLE
请问为何我使用WriteToDisk后 再读取的内容不是我保存的内容呢

### ISSUE THREAD

**Issue by hel2o** [bbdshow/gocache#1]
![图片](https://user-images.githubusercontent.com/14226648/99743826-6ee6f400-2b11-11eb-856a-c93115d6c884.png)
![图片](https://user-images.githubusercontent.com/14226648/99743861-81612d80-2b11-11eb-9be1-dcae90848e45.png)
![图片](https://user-images.githubusercontent.com/14226648/99743870-8aea9580-2b11-11eb-8c72-1eb4a93bab18.png)

落盘后的数据不对 但文件修改时间是更新了的

**Comment by bbdshow** [comment]
你好：经过测试，应该是没有问题，你看下是否用法存在差异。今天我把代码整体质量提升了一下，删除了一些过度设计，如果你还有需要欢迎你继续使用和反馈

**Comment by bbdshow** [comment]
你好：经过测试，应该是没有问题，你看下是否用法存在差异。今天我把代码整体质量提升了一下，删除了一些过度设计，如果你还有需要欢迎你继续使用和反馈 @hel2o
